name: azdo-pipeline-diagrams

on:
  push:
    paths:
      - 'azdo-pipeline-diagrams/**'
  pull_request:
    paths:
      - 'azdo-pipeline-diagrams/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: azdo-pipeline-diagrams
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
          cache-dependency-path: azdo-pipeline-diagrams/pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm test
